title: Vicente Reyes-Puerta, PhD
author: Software/ML Engineer
email: vr.web@outlook.com
description: > # this means to ignore newlines until "show_excerpts:"
  Personal website powered by the minima theme for Jekyll and hosted on GitHub

show_excerpts: false # set to true to show excerpts on the homepage

twitter_username: vreyespue
github_username:  vreyespue
linkedin_username:  vreyespue

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
theme: minima

#plugins:
# - jekyll-feed
# - jekyll-seo-tag